[project]
name = "lumi-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk>=0.3.22",
    "google-adk>=1.24.1",
    "google-genai>=1.62.0",
    "mcp[cli]>=1.26.0",
    "vertexai>=1.43.0",
]
